# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Build matrix options
matrix:
  include:
    - php: 7.2
      env: WP_TRAVISCI=travis:js
    - php: 7.0
      env: WP_TRAVISCI=travis:phpunit
    - php: 7.1
      env: WP_TRAVISCI=travis:phpunit
    - php: 7.1.9
      env: WP_TRAVISCI=travis:phpunit
    - php: 7.2
      env: WP_TRAVISCI=travis:phpunit
    - php: hhvm
      env: WP_TRAVISCI=travis:phpunit
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

env:
  - WP_VERSION=master WP_MULTISITE=1
